export const customSimpleData = [
  {
    id: 436,
    attributeName: "user_type",
    attributeDesc: null,
    showName: "用户类型 ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 437,
    attributeName: "IDFA",
    attributeDesc: null,
    showName: "IDFA ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 438,
    attributeName: "gender",
    attributeDesc: null,
    showName: "性别 ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 439,
    attributeName: "IMEI",
    attributeDesc: null,
    showName: "IMEI ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 443,
    attributeName: "credit",
    attributeDesc: null,
    showName: "积分 ",
    dataType: "NUMBER:INT",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 445,
    attributeName: "member_level",
    attributeDesc: null,
    showName: "会员等级 ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 448,
    attributeName: "phone_number",
    attributeDesc: null,
    showName: "手机号码 ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 449,
    attributeName: "last_visit_time",
    attributeDesc: null,
    showName: "最近一次访问时间 ",
    dataType: "DATETIME",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 450,
    attributeName: "memer_id",
    attributeDesc: null,
    showName: "会员ID ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 451,
    attributeName: "email",
    attributeDesc: null,
    showName: "邮箱 ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  },
  {
    id: 453,
    attributeName: "nickname",
    attributeDesc: null,
    showName: "昵称 ",
    dataType: "STRING",
    format: null,
    dict: false,
    visible: true,
    preset: false,
    remark: null
  }
]
